baseurl = "https://eoinlarkin.github.io/"
publishDir = "/"
languageCode = "en-us"
title = "in numerus veritas"
theme = "hugo-lithium"
googleAnalytics = "UA-173965746-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
summaryLength = 35


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Bookshelf"
    url = "/bookshelf/"
	weight = 2
[[menu.main]]
    name = "Heatmaps"
    url = "/heatmaps/"
	weight = 3	
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/eoinlarkin/"	
	weight = 4
[[menu.main]]
    name = "About"
    url = "/about/"
	weight = 5	

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

  # Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
  # they have to be referred from static root. Example
  #[[params.customCSS]]
  #href = "css/mystyle.css"
  
# This enables html content as part of the output
# Issue is discussed here https://github.com/rstudio/blogdown/issues/465
[markup]
    [markup.goldmark.renderer]
      unsafe = true
